{{- if .Values.containerregistry.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth
  namespace: {{ .Release.Namespace }}
stringData:
  # The only supported password format is bcrypt
  htpasswd:  {{ htpasswd .Values.global.registryUsername .Values.global.registryPassword | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "epinio-registry"
    app.kubernetes.io/instance: "epinio-registry"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "epinio-registry"
    app.kubernetes.io/instance: "epinio-registry"
  ports:
  - name: registry
    port: 5000
    targetPort: 5000

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epinio-registry
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - "epinio-registry.{{ .Values.global.domain }}"
  issuerRef:
    kind: ClusterIssuer
    name: {{ default .Values.global.tlsIssuer .Values.global.customTlsIssuer | quote }}
  secretName: epinio-registry-tls
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "kubed-registry-tls-from={{ .Release.Namespace }}" # Sync certificate to matching namespaces

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app.kubernetes.io/name: "epinio-registry"
    app.kubernetes.io/instance: "epinio-registry"
  name: registry
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.containerregistry.ingressClassName }}
  ingressClassName: "{{ .Values.containerregistry.ingressClassName }}"
  {{- end }}
  rules:
  - host: "epinio-registry.{{ .Values.global.domain }}"
    http:
      paths:
      - backend:
          service:
            name: registry
            port:
              number: 5000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - "epinio-registry.{{ .Values.global.domain }}"
    secretName: epinio-registry-tls

{{ if .Values.containerregistry.createNodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: registry-node
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "epinio-registry"
    app.kubernetes.io/instance: "epinio-registry"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: "epinio-registry"
    app.kubernetes.io/instance: "epinio-registry"
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    nodePort: 30500
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "epinio-registry"
    app.kubernetes.io/instance: "epinio-registry"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "epinio-registry"
      app.kubernetes.io/instance: "epinio-registry"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "epinio-registry"
        app.kubernetes.io/instance: "epinio-registry"
    spec:
      containers:
      - name: registry
        image: {{ .Values.containerregistry.image }}
        imagePullPolicy: {{ .Values.containerregistry.imagePullPolicy }}
        env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /etc/registry/auth/htpasswd
        volumeMounts:
        - name: registry
          mountPath: /var/lib/registry
          readOnly: false
        - name: auth
          mountPath: /etc/registry/auth
          readOnly: true
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: registry
        emptyDir: {}
      - name: auth
        secret:
          secretName: auth
{{- end }}
