{{- $registryURL := .Values.global.registryURL }}
{{- if .Values.containerregistry.enabled -}}
{{- $registryURL = (print "epinio-registry." .Values.global.domain) -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  annotations:
    epinio.suse.org/registry-namespace: {{ .Release.Namespace }}
    kubed.appscode.com/sync: kubed-sync=registry-creds
  name: registry-creds
  namespace: epinio-staging
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "{{ $registryURL }}": {
          "auth":"{{ printf "%s:%s" .Values.global.registryUsername .Values.global.registryPassword | b64enc }}",
          "username":"{{ .Values.global.registryUsername }}",
          "password":"{{ .Values.global.registryPassword }}"
        } {{- if .Values.containerregistry.enabled }} ,
        "127.0.0.1:30500": {
          "auth":"{{ printf "%s:%s" .Values.global.registryUsername .Values.global.registryPassword | b64enc }}",
          "username":"{{ .Values.global.registryUsername }}",
          "password":"{{ .Values.global.registryPassword }}"
        }
        {{- end -}}
      }
    }
