apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: epinio-s3-connection-details
  namespace: tekton-staging
stringData:
  bucket: {{ .Values.s3.bucket }}
  config: |-
    [default]
    region = {{ .Values.s3.region }}
  credentials: |-
    [default]
    aws_access_key_id     = {{ .Values.s3.accessKeyID }}
    aws_secret_access_key = {{ .Values.s3.secretAccessKey }}
  endpoint: {{ .Values.s3.endpoint }}
  useSSL: "{{ .Values.s3.useSSL }}"
