---
apiVersion: v1
kind: Namespace
metadata:
  name: epinio-staging
  annotations:
    linkerd.io/inject: enabled
  labels:
  # label so that kubed copies epinio-registry and s3 secret to this namespace
  {{- if .Values.containerregistry.enabled }}
    kubed-registry-tls-from: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.minio.enabled }}
    kubed-s3-tls-from: {{ .Release.Namespace }}
  {{- end }}
