## Default values for Epinio Helm Chart.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

# Domain which serves the Rancher UI (to access the API)
# accessControlAllowOrigin: ""

# The email address you are planning to use for getting notifications about your certificates. (default "epinio@suse.com")
email: "epinio@suse.com"

# The name of the cluster issuer to use. Epinio creates three options: 'epinio-ca', 'letsencrypt-production', and 'selfsigned-issuer'. (default "epinio-ca")
tlsIssuer: "epinio-ca"

# The domain you are planning to use for Epinio. Should be pointing to the traefik public IP (mandatory option).
domain: "localhost.omg.howdoi.website"

# The user name for authenticating all API requests.
# user: ""

# The password for authenticating all API requests.
# password: ""

# Assert to epinio that cert-manager is already installed.
# skipCertManager: false

# Assert to epinio that Linkerd is already installed.
# skipLinkerd: false

# Assert to epinio that there is a Traefik active, even if epinio cannot find it.
# skipTraefik: false

# If you are using your own S3 compatible object storage for blobs, set the following options:
# s3Endpoint: ""
# s3AccessKeyId: ""
# s3SecretAccessKey: ""
# s3Bucket: ""

# Optional
# s3Location: ""
# s3UseSSL: ""

# If you are using your own external registry, set the following options:
# --external-registry-url: ""
# --external-registry-username: ""
# --external-registry-password: ""

# Optional
# Provide namespace (or organization) of the external registry to which you have push access. It can be left empty.
# --external-registry-namespace: ""

# Use TLS when application images will be pulled by kubernetes. Only applies to the internal registry. (default "false")
# --force-kube-internal-registry-tls: ""

containerRegistryChart: "https://github.com/epinio/epinio-helm-chart/releases/download/container-registry-0.1.0/container-registry-0.1.0.tgz"
epinioChart: "https://github.com/epinio/epinio-helm-chart/releases/download/epinio-0.2.0/epinio-0.2.0.tgz"
traefikChart: "https://helm.traefik.io/traefik/traefik-10.3.4.tgz"
# installerImageOverride: "ghcr.io/epinio/epinio-installer:latest"

# Trace level for the install/uninistall hooks
traceLevel: "2"
