apiVersion: v1
name: epinio
version: "0.2.4"
appVersion: "v0.3.1"
description: The Epinio component (without dependencies)
home: https://github.com/epinio/epinio
icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
keywords:
- epinio
- paas
sources:
- https://github.com/epinio/epinio
maintainers:
- name: SUSE
  email: team@epinio.io
