apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epinio-ui
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ .Values.domain }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.tlsIssuer }}
  secretName: epinio-ui-tls
